# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HCRDA-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HCRDA-iOS
  pod 'SSZipArchive'
  pod 'AFNetworking'
  pod 'HCDebugTool'

  target 'HCRDA-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HCRDA-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
